#%RAML 1.0 NamedExample
value:
 -
    flightcode: 701
    departureDate: 2021/12/12
    origin: MAA
    destination: BLR
    passengername : Anu
    passengerage : 34
 -
    flightcode: 704
    departureDate: 2021/12/12
    origin: MAA
    destination: BLR
    passengername : Anu
    passengerage : 34