#%RAML 1.0 NamedExample

value:
    code: F206
    price: 300
    departureDate: 2021/12/12
    origin: MAA
    destination: BLR
    emptySeats: 0
    plane: 
      type: Boeing 737
      totalSeats: 150